import type { Metadata } from "next";
import "./globals.css";
import { Raleway } from 'next/font/google';
import FixedBackground from '../components/FixedBackground';

const font = Raleway({
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={font.className}>
      <body>
        <FixedBackground />
        {children}
      </body>
    </html>
  );
}
